### ISSUE TITLE
; 만 입력했을때 오류 출력이 다른 문제

### ISSUE THREAD

**Issue by ykoh42** [exgs/oh_my_minishell#37]
## 문제
`;` 만 입력했을때 command not found 가 나옴
원래는
```
bash: syntax error near unexpected token `;'
```

## 수정 중인 파일 
`execute_commands.c:` 와 이와 관련된 파일들(?)

**Comment by exgs** [comment]
; < > | 만 입력했을 때 에러처리를 하였으나,
       ;
       >
      <
      |
이런 경우에는 그냥 아무런 행동도 취하지않게 했음. 만약 저런거까지 고려하면,
    ; >
     < |
     이런 복잡한 것도 너무 많아져서...그냥 넘기는 것이 좋아보임.
     
  두번째로는 수정이 불가피한 경우에는 check_command가 int형 이였으면 좋았을 것 같음
     그리고 check_command에서  _commond not found_ 에러를 출력하는 것을 포함하고 있는데, command not found 가 아닌 에러가 check_command의 is_builtin, is_command 까지 들어가서 return (-1)을 받고 나왔을 경우 check_command를 호출하는 함수에서 return (-1) 값을 받아서 에러처리를 할 수도 있기 때문에 void 형이면 에러처리에 어려움이 있을 수도 있을 것 같음.

**Comment by exgs** [comment]
이정도선에서 마무리하는 걸로 해야할 듯
