### ISSUE TITLE
^C 하면 미니쉘 두줄 출력되는 문제

### ISSUE THREAD

**Issue by ykoh42** [exgs/oh_my_minishell#39]
## 문제
^C하면 프롬프트가 한 줄 더 추가되서 나옴

## 수정 중인 파일 
????????

**Comment by ykoh42** [comment]
아까 안됐는데 갑자기 한줄씩 출력되네

**Comment by exgs** [comment]
최신버전인지 확인해줄 수 있어??
그리고 <grep a> 만 명령어치고 여러가지 입력값 넣어본 후에 CTRL+C하면 어때?

**Comment by ykoh42** [comment]
@exgs 명령어치고 여러가지 입력값 넣은다음에 ^C해도 bash랑 동일하게 나오는것같아 잘되는듯

@PennyBlack2008 
@kohyounghwan 

이슈 닫아도 될것같은데 닫아도 되겠습니까~?

**Comment by exgs** [comment]
넵 제가 닫겠습니다!
