### ISSUE TITLE
^D하면 exit 출력 안되는 문제

### ISSUE THREAD

**Issue by ykoh42** [exgs/oh_my_minishell#40]
## 문제
bash 에서 `^D`하면 exit라는 글자가 쳐지면서 종료됨

minishell에서는 exit라는 글자 없이 종료됨

## 수정 중인 파일 
????????

**Comment by exgs** [comment]
bash에서 `^D` 하면, 개행없이 exit 이 출력되고,
                ` exit` 를 쳤을 때,  개행 후에 exit이 출력되면서 종료되는 것 같음. 수정해보도록 함!

**Comment by exgs** [comment]
완전히 해결된 것으로 보여서 close하겠습니다.
