### ISSUE TITLE
echo hello 후 ^D 하면 출력 안되는 문제

### ISSUE THREAD

**Issue by ykoh42** [exgs/oh_my_minishell#41]
## 문제
`minishell`에서 `echo hello` 후 `^D` 연타하고 `enter`치면 출력 안되는 문제

`bash`에서는 출력 됨

## 수정 중인 파일 
????????

**Comment by exgs** [comment]
main.c 에서 ->  // g_flag[CTRL_D] = 1; 주석처리하면
<echo hello^D> 이렇게 치면 hello 잘 출력되고, 연타하면 아예 빠져나가게 되던데 이 정도로 개선하는건 어떰??
bash에서 CTRL+D 아예 문자로써 입력은 안되서 아예 영향을 못주기때문에 연타하건말건 잘 실행되는거라고 생각했었음.

**Comment by ykoh42** [comment]
1. Try ctrl-D in an empty prompt
2. Try ctrl-D in a prompt after you wrote some stuff
3. Try ctrl-D after running a blocking command like cat or grep without arguments

여기서 2번이 이 이슈에 해당되는 건데 애매하긴하넹 

2번 통과될 것같으면 이슈 닫아도 될것같고 통과안될것같으면 수정하고 넘어가야 할것같고..

어떻게 하는게 좋을까..

해결방법 생각해본건 gnl 사용안하고 한글자씩 받아오면 해결할 수있을것같긴한데

**Comment by exgs** [comment]
g_flag[CTRL_D] 주석처리 안해도 지금 2번 echo hello + ^D 연타해도, 한번만 입력되고 그 이후에는 입력이 안됨.
형이 해결한 문제했음??@kohyounghwan

**Comment by exgs** [comment]
pull request #64 에서 해결함
