### ISSUE TITLE
echo와 리디렉션을 같이 사용했을 때, 제대로 동작하지 않는 문제.

### ISSUE THREAD

**Issue by exgs** [exgs/oh_my_minishell#47]
1. 큰따움표 작은 따움표 안에 리디렉션 기호가 있는 경우 이를 문자로 인식하지 않는 문제.
echo "aa > bb" 하면 bb 파일이 생성된다. ~~#48~~ 
2. 표준출력에서는 `echo "sdfsd > sd"`이 잘 출력된다.
하지만,  리디렉션과 섞이는 경우 `echo "111 > 222" > test.txt` test.txt 파일에 `111 > 222 > test.txt`까지 써지는 문제
#50 @PennyBlack2008

**Comment by PennyBlack2008** [comment]
해결했습니다~
