### ISSUE TITLE
cd $OLDPWD, cd $PWD 가 안되는 문제

### ISSUE THREAD

**Issue by PennyBlack2008** [exgs/oh_my_minishell#52]
jikang 이 예전에는 path 랑 argv를 미리 환경변수 바꿔주는 형식으로 했었어서 예전에는 환경변수 변형이 잘되었지만, 현재는 그 방식을 사용하지 않고 line 이 그대로 들어가기 때문에,

execute_cd에서 직접 `path` 와 `argv`를 refine_line 함수로 변형해주어야 한다.
그런데, 제가 테스트 해본 결과로는 , execute_cd 함수에서
60번 줄의 `path = argv[1];`를 주석 처리하고 `path = refine_line(argv[1]);`를 해주면 환경변수가 적용되어 잘 변형이되는데,

문제는 제가 free 를 못 잡겠습니다. 왜 free 가 잘 안되는 지, 만약 좋은 의견있으면 알려주세요~

**Comment by ykoh42** [comment]
누수부분 살펴볼게용

**Comment by PennyBlack2008** [comment]
commit a4316295e54e7b9544c136fcac2bfb8fd0a46fc0
해결! by Ykoh
