### ISSUE TITLE
 'pwd', "pwd", 'env', "env" 등등이 작동하게 해야한다.

### ISSUE THREAD

**Issue by PennyBlack2008** [exgs/oh_my_minishell#54]
_정말 웃긴게,
다른 명령어 같은 경우는 대부분 문자열로 받지만,_ 

pwd 와 env의 경우에는 bash에서 실행을 한다.
**수정**: **옵션 없이는 다 실행된다 예를 들어 echo -n 이런거는 안되지만 echo 혼자서는 된다**
-------------------------------------------------------------------
check_command에서 단순히 추가해주면 좋은 데, 어떻게 깔끔하게 할 수 있는 방법이 없을 까 고민중입니다.

**Comment by ykoh42** [comment]
* `$> 'pwd'`
* `$> "pwd"`
* `$> 'pwd'`
* `$> "pwd"`

이거 동작해야한다는것맞지?

**Comment by PennyBlack2008** [comment]
다음 커밋 번호에서 9b227fb473fea0fe4ef4d3d91f62a7435943030c
해결했습니다.
