### ISSUE TITLE
echo "\"" 출력문제

### ISSUE THREAD

**Issue by exgs** [exgs/oh_my_minishell#66]
<img width="422" alt="스크린샷 2021-01-20 오전 2 46 28" src="https://user-images.githubusercontent.com/56223639/105073082-edd4ba80-5ac9-11eb-8982-a93adcf5d4a3.png">
@PennyBlack2008

**Comment by PennyBlack2008** [comment]
\n 이 출력되도록 하다가 미쳐 고려하지 못했던 문제였음.

둘다 되도록 생각보다 쉽게 끝냄
