### ISSUE TITLE
echo "pwd is$PWDhome is $HOME" segfault에러

### ISSUE THREAD

**Issue by exgs** [exgs/oh_my_minishell#67]
<img width="1255" alt="스크린샷 2021-01-20 오전 3 27 18" src="https://user-images.githubusercontent.com/56223639/105077316-b23cef00-5acf-11eb-9f8d-93431cfcefa4.png">
https://www.notion.so/Environment-Variables-6e0f1663ee614465ba23049222ec14dc
@PennyBlack2008

**Comment by PennyBlack2008** [comment]
에러처리함. 세크폴트 고침

하지만 bash 처럼 동작하지 않음
