### ISSUE TITLE
^C, ^D 이후에 echo $? 의 출력값

### ISSUE THREAD

**Issue by exgs** [exgs/oh_my_minishell#68]
https://www.notion.so/C-D-echo-022edd8814f24987a95818f49b1aaf17

^D, ^C, ^\ 로 으로 종료시에
echo $? 값이 0이 아닌 값이 배정된다.
ex) cat, grep 실행프로그램을 위 명령어로 종료시에 130
ex) 그냥 입력창에서 위 명령어를 사용하면 1

**Comment by ykoh42** [comment]
PR 올린거에 댓글달았음

**Comment by exgs** [comment]
문제 해결 
backup 브랜치 : a2eb9d2f0fbc222b88c52f7b47b482c430a7065e
